silverwork_dbt:
  target: stage
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      database: "{{ env_var('SNOWFLAKE_DATABASE') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE') }}"
      schema: "{{ env_var('SNOWFLAKE_SCHEMA') }}"
      threads: 10
    stage:
      type: bigquery
      method: oauth-secrets
      token: "{{ env_var('BIGQUERY_OAUTH_TOKEN') }}"
      project: "{{ env_var('BIGQUERY_PROJECT_ID') }}"
      dataset: "{{ env_var('BIGQUERY_DATASET_ID') }}"
      dataproc_region: us-central1
      gcs_bucket: silverwork-bucket
      dataproc_cluster_name: dbt-cluster
      threads: 10
