name: Check PR

on:
  pull_request:
    branches: [ "main", "develop" ]

env:
  working-directory: silverwork_dbt
  DBT_PROFILES_DIR: ./
  BIGQUERY_PROJECT_ID: ${{ vars.DBT_BIGQUERY_PROJECT_ID }}
  BIGQUERY_DATASET_ID: ${{ vars.DBT_BIGQUERY_DATASET_ID }}
  BIGQUERY_OAUTH_TOKEN: ${{ secrets.BIGQUERY_OAUTH_TOKEN }}

  SNOWFLAKE_ACCOUNT: ${{ vars.SNOWFLAKE_ACCOUNT }}
  SNOWFLAKE_DATABASE: ${{ vars.SNOWFLAKE_DATABASE }}
  SNOWFLAKE_WAREHOUSE: ${{ vars.SNOWFLAKE_WAREHOUSE }}
  SNOWFLAKE_USER: ${{ vars.SNOWFLAKE_USER }}
  SNOWFLAKE_PASSWORD: ${{secrets.SNOWFLAKE_PASSWORD}}
  SNOWFLAKE_ROLE: ${{ vars.SNOWFLAKE_ROLE }}
  SNOWFLAKE_SCHEMA: ${{ vars.SNOWFLAKE_SCHEMA }} 
  
jobs:
  build:
    name: install and build dbt
    runs-on: ubuntu-latest
        
    steps:          
      - name: Install Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.16
          
      - name: Checkout Repo
        uses: actions/checkout@v2
        
      - name: Set up Snowflake environment
        if: ${{ github.base_ref == 'develop' }}
        run: |
          pip install dbt-snowflake pandas
          dbt --version
          dbt deps
        env:
          DBT_TARGET: dev
        working-directory: ${{ env.working-directory }}

      - name: Set up BigQuery environment
        if: ${{ github.base_ref == 'main' }}
        run: |
          pip install dbt-snowflake pandas
          dbt --version
          dbt deps
        env:
          DBT_TARGET: stage
        working-directory: ${{ env.working-directory }}
      
      - name: Check source connection
        run: echo "dbt debug --target $DBT_TARGET"
        working-directory: ${{ env.working-directory }}
        
      - name: Run dbt models
        run: echo "dbt run --target $DBT_TARGET"
        working-directory: ${{ env.working-directory }}
        
      - name: Test dbt models
        run: echo "dbt test --target $DBT_TARGET"
        working-directory: ${{ env.working-directory }}
