name: Check PR

on:
  pull_request:
    branches: [ "main", "develop" ]

env:
  working-directory: silverwork_dbt
  DBT_PROFILES_DIR: ./
  BIGQUERY_PROJECT_ID: ${{ vars.DBT_BIGQUERY_PROJECT_ID }}
  BIGQUERY_DATASET_ID: ${{ vars.DBT_BIGQUERY_DATASET_ID }}
  BIGQUERY_SERVICE_FILE: ./dbt-service-account.jso
  KEYFILE_CONTENTS: ${{secrets.KEYFILE_CONTENTS}}
  
  SNOWFLAKE_ACCOUNT: ${{ vars.SNOWFLAKE_ACCOUNT }}
  SNOWFLAKE_DATABASE: ${{ vars.SNOWFLAKE_DATABASE }}
  SNOWFLAKE_WAREHOUSE: ${{ vars.SNOWFLAKE_WAREHOUSE }}
  SNOWFLAKE_USER: ${{ vars.SNOWFLAKE_USER }}
  SNOWFLAKE_PASSWORD: ${{secrets.SNOWFLAKE_PASSWORD}}
  SNOWFLAKE_ROLE: ${{ vars.SNOWFLAKE_ROLE }}
  SNOWFLAKE_SCHEMA: ${{ vars.SNOWFLAKE_SCHEMA }}

jobs:
  build:
    name: install and build dbt
    runs-on: ubuntu-latest
        
    steps:          
      - name: branch
        run: |
          echo ${{ github.head_ref }}
